---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: ucp-drydock
  labels:
    name: ucp-drydock-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: ucp-drydock-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:

    # MaaS IPs
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .genesis.ip
      dest:
        path: .values.conf.drydock.maasdriver.maas_api_url
        pattern: 'MAAS_IP'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .node_ports.maas_api
      dest:
        path: .values.conf.drydock.maasdriver.maas_api_url
        pattern: 'MAAS_PORT'

data:
  values:
    pod:
      security_context:
        drydock:
          pod:
            # NOTE: Drydock has a hardcoded path to SSH key that
            # uses root home directory, default `nobody` user
            # does not have have the access to keys in the root
            # directory, consequently Drydock fails to connect to
            # the Libvirt host using SSH.
            # Remove this workaround when Drydock is fixed.
            runAsUser: 0
    manifests:
      secret_ssh_key: true
    network:
      api:
        nodeport:
          enabled: true
    replicas:
      drydock: 1
    conf:
      ssh:
        private_key: |-
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEAt273lGWAdwslQMwFxzfJpmPDBZkF9pnI5lkQ5OPFcK05F2AT
          BM99t7rN1nD2YKsSDZYkjgR31A6mWWW1HNtKEfKQCvxHzFBgFhgRSQyJ6WDvHRhj
          RZHKGNlRFasvtiHdDMdKdlXPr15pS28GZ6HntDRbwkslmE2phRAh3ox3RN7K9ZxN
          4xGWYPD03J3bQgxp1hMVdhAvwggcklKz3QMhk8RwNL5n/tRnZ3MqfGkQwQLB+y1p
          +BYlZst9EZ9tsY07Oxe+AUV2v7GtM83bi/5Xo830iwBASDg4e1htSnUlHh9hATGb
          xr0Tygki6VvV1R+NoJY0k/8P6sDmyjiYdl25RwIDAQABAoIBAAj2UP5dHzOxxbYu
          wbGEFkQc57BkU5hC1z/55gto3YKt0/ZCaWt4v8m0RM5PYppCgXVMeqi9qyUfOh1w
          DLNGO4447bS7sr5WxvsNXfrVs/9FDym6wU7q2pbwNzf5zzD04pn3OrohYy5MTJS0
          7fkuPeXeEQWjKkkQslGgAiefcUxaCRg5UnIziNoKlsKCfZ/vhcE6m0o+sye01YiD
          c1MhPJYjQfcS0ZqVZ3fTH5IW4Tq75CpsgomgAwOt02Hw/WZC6xgCGz8ElOB50WKs
          wk4HtT5wVDRFirVsjr85fWz0BrnkgV0Ls4M5HoYyQ8g6kCjMOXQsqc4cd6oeQb7g
          BShnDYECgYEA5Fh6wT3s8h6jd7LX4PwiqkNaDoArfv3rMZQZ9FYBUeEyvYujKqsN
          sGJa+Hl1S9Dv6s/hkla7Ey7SMDeTXz/DZwC9WM+Ro+Eb3Xf0LDrKCy37oNxhkb61
          7PkX4BxnMRARzGbsjicVMRRElcGVUzwsaORcdYrfbJi5HxtghtdadyECgYEAzaYN
          WTIEQfRQ8VKbl+aFWxiHvIn2KuWxXbGNB0aur5uOVO7CmcwZsuyVICppWaz8Ye/r
          WH+7mYTRj2OICBu8m955ebs68prkVV7v1SaCjD+mTY7R7muBpEVPsKRso8qi/JLU
          R27+5DQvhrhMJ9NIWaFaXhMD/kG6FFgyaOSNa2cCgYEAnpWgc1KZm7GRn9DyQst5
          G7x47/ctvh2E2ULdH6cXdZEsFx3CbSCs+iHkwgpAXy41YWOMaoCXngP3cAs4636y
          K3gFCIfnwuPU4WOsjYcqyMbfqeFEVd8YJAL/BONU+2sIoWedxD/6ZMKJu2PdXBg/
          U329hNi0wIv0jVkLGbq4lmECgYBGLEJjzFBtnQu9vR2A0NVyh0VSDZWlf6ltOjfQ
          Yssa+y6vRqW6y019o4MjbbVzNzcLyE17bmK6ePr1PdZeRfCvE1RKOJxdyoLdqr6V
          8kUbzGBYGMMD40Vio5AUy5aSsYO6QfQTyAlMH46UHvFFqbAHfaqTbVOwgAcaCBpz
          doHXQwKBgCXBWUDCC84F8PTV4xtYWqaftPhu9rewacInSfmrrqUW0cgOPxWEM1BO
          dFB/BxyieoghGP281VcrnJGuh3j6aqb/rdcWmZ0qgAzSJMls/0+d2RbatRBEOn2K
          sAXnT+qmj2jPiqsAlqtLdCounRKbazUVkIFu+4sCaORdXFJYoqVK
          -----END RSA PRIVATE KEY-----
      drydock:
        plugins:
          oob_driver:
            - 'drydock_provisioner.drivers.oob.pyghmi_driver.driver.PyghmiDriver'
            - 'drydock_provisioner.drivers.oob.libvirt_driver.driver.LibvirtDriver'
        database:
          pool_size: 200
        maasdriver:
          maas_api_url: http://MAAS_IP:MAAS_PORT/MAAS
...
