---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openvswitch
  layeringDefinition:
    abstract: false
    layer: global
  labels:
    name: openvswitch-global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.openvswitch
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.openvswitch
      dest:
        path: .values.images.tags
data:
  chart_name: openvswitch
  release: openvswitch
  namespace: openstack
  wait:
    timeout: 900
    labels:
      release_group: airship-openvswitch
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-openvswitch
  values:
    labels:
      ovs:
        node_selector_key: openvswitch
        node_selector_value: enabled
    pod:
      resources:
        enabled: true
        ovs:
          vswitchd:
            requests:
              memory: "500Mi"
              cpu: "2"
            limits:
              memory: "1Gi"
              cpu: "2"
              hugepages-2Mi: "1Gi"
    conf:
      ovs_dpdk:
        enabled: true
        hugepages_mountpath: /dev/hugepages
        vhostuser_socket_dir: vhostuser
        socket_memory: 1024
  dependencies:
    - openvswitch-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openvswitch-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.openvswitch-htk
      dest:
        path: .source
data:
  chart_name: openvswitch-htk
  release: openvswitch-htk
  namespace: openvswitch-htk
  values: {}
  dependencies: []
...
