---
schema: pegleg/SoftwareVersions/v1
metadata:
  labels:
    name: software-versions-airsloop
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: software-versions-global
    actions:
      - method: merge
        path: .
  name: software-versions
  replacement: true
  schema: metadata/Document/v1
  storagePolicy: cleartext
data:
  images:
    osh:
      glance:
        glance_db_sync: "docker.io/openstackhelm/glance:rocky-ubuntu_bionic"
        db_init: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        db_drop: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_user: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_service: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_endpoints: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        glance_api: "docker.io/openstackhelm/glance:rocky-ubuntu_bionic"
        glance_registry: "docker.io/openstackhelm/glance:rocky-ubuntu_bionic"
        bootstrap: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        #glance_storage_init: "docker.io/openstackhelm/ceph-config-helper:latest-opensuse_15"
      keystone:
        bootstrap: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        db_init: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        keystone_db_sync: "docker.io/openstackhelm/keystone:rocky-ubuntu_bionic"
        db_drop: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_user: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        keystone_fernet_setup: "docker.io/openstackhelm/keystone:rocky-ubuntu_bionic"
        keystone_fernet_rotate: "docker.io/openstackhelm/keystone:rocky-ubuntu_bionic"
        keystone_credential_setup: "docker.io/openstackhelm/keystone:rocky-ubuntu_bionic"
        keystone_credential_rotate: "docker.io/openstackhelm/keystone:rocky-ubuntu_bionic"
        keystone_api: "docker.io/openstackhelm/keystone:rocky-ubuntu_bionic"
        keystone_domain_manage: "docker.io/openstackhelm/keystone:rocky-ubuntu_bionic"
      ingress:
        ingress_module_init: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        ingress_routed_vip: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
      libvirt:
        libvirt: "docker.io/openstackhelm/libvirt:latest-ubuntu_bionic"
      mariadb:
        prometheus_mysql_exporter_helm_tests: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
      neutron:
        bootstrap: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        db_init: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        db_drop: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_user: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_service: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_endpoints: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        neutron_db_sync: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        neutron_dhcp: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        neutron_l3: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        neutron_linuxbridge_agent: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        neutron_metadata: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        neutron_openvswitch_agent: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        neutron_server: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        neutron_sriov_agent: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
        neutron_sriov_agent_init: "docker.io/openstackhelm/neutron:rocky-ubuntu_bionic"
      nova:
        bootstrap: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        db_drop: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        db_init: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_user: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_service: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        ks_endpoints: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        nova_api: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_cell_setup: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_cell_setup_init: "docker.io/openstackhelm/heat:rocky-ubuntu_bionic"
        nova_compute: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_compute_ssh: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_conductor: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_consoleauth: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_db_sync: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_novncproxy: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_novncproxy_assets: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_placement: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_scheduler: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_spiceproxy: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_spiceproxy_assets: "docker.io/openstackhelm/nova:rocky-ubuntu_bionic"
        nova_service_cleaner: "docker.io/openstackhelm/ceph-config-helper:latest-opensuse_15"
      openvswitch:
        openvswitch_db_server: "docker.io/openstackhelm/openvswitch:latest-ubuntu_bionic-dpdk"
        openvswitch_vswitchd: "docker.io/openstackhelm/openvswitch:latest-ubuntu_bionic-dpdk"
      #rabbitmq:
      #  prometheus_rabbitmq_exporter_helm_tests: "docker.io/openstackhelm/heat:rocky-opensuse_15-20190819"
      #  rabbitmq_init: "docker.io/openstackhelm/heat:rocky-opensuse_15-20190819"
